name: Manual Broken Link Checker
on:
  workflow_dispatch:
    inputs:
      test_url:
        description: 'The URL to perform link checking on'
        required: true
jobs:
  check_links:
    runs-on: ubuntu-16.04
    steps:
    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: Install Muffet
      run: GO111MODULE=on go get -u github.com/raviqqe/muffet/v2
    - name: Build
      run: go build
    - name: Run
      run: ./broken-link-checker ${{ github.event.inputs.test_url }}
      env:
        VERBOSE: true
        MAX_CONNECTIONS: 5
        TIMEOUT_SECONDS: 10
        EXCLUSIONS: linkedin.com,facebook.com
